### ISSUE TITLE
Core 2016 GUI not showing up roblox removed topbarframe?

### ISSUE THREAD

**Issue by Rezy774** [scotdotwtf/lua-projects#6]
i hope specowos updates it :(

**Comment by ImLoadingUuU** [comment]
a fixed fork by me,you can try it
```lua
--// config settings
getgenv().config = {
    old_console = true,
    old_plist = true,
    old_graphics = false,
    dev = true
}

--// mods
getgenv().mods = {
    fps_counter = true,
    built_in_silentre = true,
    c00l_mode = false
}

loadstring(game:HttpGet("https://raw.githubusercontent.com/ImLoadingUuU/lua-projects/main/project%202016%3A%20Remastered/Main.lua"))()
```

**Comment by scotdotwtf** [comment]
I merged! yipee lol. Probably still doesn't work tho, can't test because I don't have an executor.

**Comment by Rezy774** [comment]
use delta executor or i can send me over the script and ill try it on android

**Comment by scotdotwtf** [comment]
As you wish:

```lua
--// config settings
getgenv().config = {
    old_console = true,
    old_plist = true,
    old_graphics = true,
    dev = false
}

--// mods
getgenv().mods = {
    fps_counter = false,
    built_in_silentre = false,
    c00l_mode = false
}

loadstring(game:HttpGet("https://raw.githubusercontent.com/scotdotwtf/lua-projects/main/project%202016%3A%20Remastered/Main.lua"))()
```

**Comment by Rezy774** [comment]
ok

**Comment by Rezy774** [comment]
i hope it works

**Comment by scotdotwtf** [comment]
lol

**Comment by Rezy774** [comment]
bro i hate key executors fr

**Comment by Rezy774** [comment]
IT WORKS ON MOBILE

**Comment by Rezy774** [comment]
TYYYYYYY

**Comment by Rezy774** [comment]
also make the topbar larger to support samsung galaxy S10

**Comment by scotdotwtf** [comment]
Idk, maybe in the future lol

**Comment by Rezy774** [comment]
Dang

**Comment by Rezy774** [comment]
It does not fit edges of screen its like cut off imloadinguuu’s script fit the edges of the screen the script executes and works as normal but the topbar needs to be like stretched or longer idk lua so i hope its not hard. Idk if its my phone or smtn
![image](https://github.com/scotdotwtf/lua-projects/assets/128003302/ab1ae66b-5eb7-486a-ab05-6e347c198232) im on a samsung galaxy S10

**Comment by Rezy774** [comment]
Little issue it executes first but when you go in to second game it crashes on delta executor

**Comment by Rezy774** [comment]
Fix

**Comment by Rezy774** [comment]
And health stays white after death

**Comment by ImLoadingUuU** [comment]
unable to start fluxus bye

**Comment by RobloxLoadingGui** [comment]
I does not work anymore
